---
openapi: 3.1.0
paths:
  /.well-known/jwks.json:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
      summary: Get Jwks
      tags:
        - Jwks Resource
  /.well-known/openid-credential-issuer:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
      summary: Get Metadata
      tags:
        - Issuer Metadata Resource
  /credential:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CredentialRequest"
        required: true
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Issue Credential
      tags:
        - Credential Resource
components:
  schemas:
    CredentialRequest:
      type: object
      properties:
        format:
          type: string
        credential_type:
          type: string
        subject_syntax_type:
          type: string
        subject_syntax:
          type: string
info:
  title: issuer-service API
  version: 1.0.0-SNAPSHOT
